### ISSUE TITLE
Create redirect payment method form

### ISSUE THREAD

**Issue by mcspronko** [mcspronko/liqpay-magento2#12]
What should be done:
* New payment method with the title "LiqPay Redirect" should be rendered on the checkout payment page
* The payment method should include a billing address and a button "Proceed to LiqPay"

It should be created in the Pronko_LiqPayRedirect extension.

LiqPay Redirect payment method code should be pronko_liqpay_redirect

**Comment by ProkopovVitaliy** [comment]
Will take this task

**Comment by ProkopovVitaliy** [comment]
@mcspronko for this method, have to be created `System -> Configuration -> Sales -> Payment Methods ` ?

**Comment by mcspronko** [comment]
As we discussed, let’s have a switcher and only one field for title. So we will have only switcher select field Connection Type
