### ISSUE TITLE
Add basic LiqPay configuration settings

### ISSUE THREAD

**Issue by mcspronko** [mcspronko/liqpay-magento2#3]
What should be done:
* Add new configuration settings under Stores -> Configuration -> Sales -> Payment Methods -> LiqPay
* "General Settings" section
  * "Enabled", select field, Yes/No
  * "Title", text field
  * "Mode", select field, Production/Sandbox
* "Account Settings" section
  * "Sandbox Credentials" section 
    * "Public Key", text field
    * "Private Key", text field
  * "Production Credentials" section
    * "Public Key", text field
    * "Private Key", text field

**Comment by ProkopovVitaliy** [comment]
I will take it.

**Comment by mcspronko** [comment]
Assigned.
