### ISSUE TITLE
Exception when installing extension with composers config command

### ISSUE THREAD

**Issue by codeinnovers** [mcspronko/liqpay-magento2#35]
Running below command is throwing Seld\JsonLint\ParsingException

> php composer.phar config repositories.pronko-liqpay git@github.com:mcspronko/liqpay-magento2.git

![parser-error](https://user-images.githubusercontent.com/25947503/63918396-40877f80-ca5a-11e9-93ea-16f0c66bc6ff.png)

**Comment by mcspronko** [comment]
Please use this command:

composer config repositories.pronko-liqpay git git@github.com:mcspronko/liqpay-magento2.git

**Comment by codeinnovers** [comment]
Yes I was about to push with an update in README.md
