### ISSUE TITLE
Create Payment Form on Checkout Payment Page

### ISSUE THREAD

**Issue by mcspronko** [mcspronko/liqpay-magento2#4]
What should be done:
* Payment form should be created using UI Component (JS and HTML files) and added via checkout_index_index.xml file
* Payment form should include a LiqPay title 
* Payment form should have the following fields:
  * Card Number
  * Expiration Month
  * Expiration Year
  * CVV code
* Place Order button

**Comment by mcspronko** [comment]
Currently, in order to send a capture/auth transaction to LiqPay on sandbox mode, the PCI DSS certificate is required. LiqPay support said that they can't process without PCI DSS certificate.

**Comment by mcspronko** [comment]
LiqPay support confirmed that the server-server communication can be tested with the sandbox mode with cards.

**Comment by ProkopovVitaliy** [comment]
I will work on this one.

**Comment by ProkopovVitaliy** [comment]
@mcspronko When i started work on it i found there are ready created Ui component and payment form. What i should to do ?

**Comment by mcspronko** [comment]
@ProkopovVitaliy Make sure that it works and renders the payment form on the checkout payment page. The code you see is the right one, however, it has to be double-checked, maybe some parts are missing.
