### ISSUE TITLE
Create basic redirect directory structure

### ISSUE THREAD

**Issue by mcspronko** [mcspronko/liqpay-magento2#7]
The Pronko_LiqPayRedirect extension represents the LiqPay Checkout integration (see https://www.liqpay.ua/documentation/api/aquiring/checkout/ page) which redirects a customer to a LiqPay server with a payment form.

What should be included as part of this task:

see the checkout directory as an example:
 * registration.php
 * composer.json
 * etc/module.xml

**Comment by underser** [comment]
working.
